# Generated by Django 4.2.13 on 2024-06-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="endtime",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-06-27 00:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="nottodo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="starttime",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-06-27 00:00"
            ),
            preserve_default=False,
        ),
    ]
