# Generated by Django 4.2.13 on 2024-06-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listapp", "0002_taskmodel_endtime_taskmodel_nottodo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel", name="endtime", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="taskmodel", name="starttime", field=models.DateTimeField(),
        ),
    ]
