# Generated by Django 4.2.13 on 2024-06-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listapp", "0003_alter_taskmodel_endtime_alter_taskmodel_starttime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="nottodo",
            field=models.CharField(max_length=100),
        ),
    ]
