# Generated by Django 4.2.13 on 2024-07-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listapp", "0004_alter_taskmodel_nottodo"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="memo",
            field=models.TextField(default="2024-07-02 00:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="progress",
            field=models.CharField(default="check", max_length=100),
            preserve_default=False,
        ),
    ]
