# Generated by Django 4.2.13 on 2024-07-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listapp", "0006_alter_taskmodel_memo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="memo",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
