# Generated by Django 4.2.13 on 2024-07-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listapp", "0007_alter_taskmodel_memo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="endtime",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="starttime",
            field=models.CharField(max_length=100),
        ),
    ]
